name: "tests"

on:
  push:
    branches: ["0.x"]
  pull_request:
    branches: ["0.x"]

jobs:
  phpunit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php_version: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]
    runs-on: ${{ matrix.os }}
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - name: Install dependencies
        run: composer install --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
